### ISSUE TITLE
Improve blog repo CI

### ISSUE THREAD

**Issue by ran-huang** [pingcap/blog#577]
- [x] Add external link check https://github.com/pingcap/blog/pull/623
- [x] Run markdownlint check on commit (which now seems triggered only when PR is merged) 
- [x] Migrate docs check to blog #579  
- [x] Add check for front matters #619 
- [x] Add check for Chinese punctuation #608

**Comment by ran-huang** [comment]
🎉 All planned checks are added.
